# Generated by Django 5.2.6 on 2025-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.CharField(max_length=200)),
                ('brother', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_folder', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('register_id', models.CharField(default='0', max_length=200)),
                ('ex_id', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
