# Generated by Django 5.2.6 on 2025-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='ex_id',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='folder',
            name='register_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
