# Generated by Django 5.2.6 on 2025-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorios', '0002_folder_ex_id_folder_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrtory', models.CharField(max_length=200)),
                ('brother', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
