# Generated by Django 5.2.6 on 2025-10-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('territorios', '0003_entregados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregados',
            old_name='terrtory',
            new_name='territory',
        ),
    ]
